services:
  - type: web
    name: wiserbond-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: bash start.sh
    plan: free
    envVars:
      - key: OPENAI_API_KEY
        sync: false  # Render에서 직접 관리함을 의미
